export { HomePage } from './HomePage'
export { LoginPage } from './LoginPage'
export { RegisterPage } from './RegisterPage'
export { HostelDetailPage } from './HostelDetailPage'
export { HostelBookingListPage } from './HostelBookingListPage'