export { HostelDetail } from './HostelDetail'
export { HostelList } from './HostelList'
export { HostelBookingList } from './HostelBookingList'
export { HostelLocation } from './HostelLocation'
export { HostelCarousel } from './HostelCarousel'